version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: plant_shop
      MYSQL_ROOT_PASSWORD: 1234

