version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    image: ${APP_IMAGE}
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod